"""Crear tabla asignaturas_profesores_clases

Revision ID: 0e26c9401458
Revises: dba902d88c90
Create Date: 2025-04-08 11:33:23.085355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e26c9401458'
down_revision = 'dba902d88c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaturas_profesores_clases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_profesor_id', sa.Integer(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignatura_profesor_id'], ['asignaturas_profesores.id'], ),
    sa.ForeignKeyConstraint(['clase_id'], ['clases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asignatura_profesor_id', 'clase_id', name='uix_asignatura_profesor_clase')
    )
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_column('es_fijo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_fijo', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.drop_table('asignaturas_profesores_clases')
    # ### end Alembic commands ###
