"""Crear tabla disponibilidad_comun

Revision ID: 47ace0ff34b7
Revises: 0e26c9401458
Create Date: 2025-04-08 13:09:10.680000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ace0ff34b7'
down_revision = '0e26c9401458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilidad_comun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.String(length=15), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icono', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dia', 'hora', name='uq_disponibilidad_comun_dia_hora')
    )
    with op.batch_alter_table('disponibilidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disponibilidades', schema=None) as batch_op:
        batch_op.drop_column('motivo')

    op.drop_table('disponibilidad_comun')
    # ### end Alembic commands ###
