"""remove unido_con_clase_id from horarios

Revision ID: 499b01e9e067
Revises: initial_schema
Create Date: 2025-04-09 13:14:11.705323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499b01e9e067'
down_revision = 'initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.alter_column('dia',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('hora',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.drop_constraint('horarios_unido_con_clase_id_fkey', type_='foreignkey')
        batch_op.drop_column('unido_con_clase_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unido_con_clase_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('horarios_unido_con_clase_id_fkey', 'clases', ['unido_con_clase_id'], ['id'])
        batch_op.alter_column('hora',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('dia',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
