"""empty message

Revision ID: 9311d6fb05a5
Revises: f75839616d7d
Create Date: 2025-04-08 10:11:25.533107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9311d6fb05a5'
down_revision = 'f75839616d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disponibilidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('hora',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint('disponibilidades_profesor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profesores', ['profesor_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('motivo')

    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('hora',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint('uq_horario_clase_dia_hora', type_='unique')
        batch_op.drop_constraint('horarios_clase_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('horarios_modificado_por_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clases', ['clase_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('fecha_asignacion')
        batch_op.drop_column('modificado_por')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modificado_por', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_asignacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('horarios_modificado_por_fkey', 'usuarios', ['modificado_por'], ['id'])
        batch_op.create_foreign_key('horarios_clase_id_fkey', 'clases', ['clase_id'], ['id'])
        batch_op.create_unique_constraint('uq_horario_clase_dia_hora', ['clase_id', 'dia', 'hora'])
        batch_op.alter_column('hora',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('fecha_modificacion')
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('disponibilidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('disponibilidades_profesor_id_fkey', 'profesores', ['profesor_id'], ['id'])
        batch_op.alter_column('hora',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
