"""Allow NULL values in asignatura_profesor_id

Revision ID: a0fdea89625b
Revises: 
Create Date: 2025-04-10 11:23:10.916821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0fdea89625b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades_especiales', schema=None) as batch_op:
        batch_op.alter_column('dia',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'#3498db'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('uq_actividad_especial_dia_hora', type_='unique')

    with op.batch_alter_table('asignaturas_profesores_clases', schema=None) as batch_op:
        batch_op.alter_column('asignatura_profesor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.alter_column('es_actividad_especial',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.alter_column('es_actividad_especial',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('asignaturas_profesores_clases', schema=None) as batch_op:
        batch_op.alter_column('asignatura_profesor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('actividades_especiales', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_actividad_especial_dia_hora', ['dia', 'hora'])
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('color',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=7),
               nullable=False,
               existing_server_default=sa.text("'#3498db'::character varying"))
        batch_op.alter_column('dia',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
