"""Add special activity columns to horarios table

Revision ID: add_special_activity_columns
Revises: 803df055cd38
Create Date: 2024-04-09 13:07:56.311374

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_special_activity_columns'
down_revision = '803df055cd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_actividad_especial', sa.Boolean(), nullable=True, server_default='false'))
        batch_op.add_column(sa.Column('nombre_actividad_especial', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('color_actividad_especial', sa.String(length=7), nullable=True))
        batch_op.alter_column('asignatura_id', existing_type=sa.Integer(), nullable=True)
        batch_op.alter_column('profesor_id', existing_type=sa.Integer(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.alter_column('profesor_id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('asignatura_id', existing_type=sa.Integer(), nullable=False)
        batch_op.drop_column('color_actividad_especial')
        batch_op.drop_column('nombre_actividad_especial')
        batch_op.drop_column('es_actividad_especial')

    # ### end Alembic commands ### 