"""Agregar campo es_fijo a la tabla horarios

Revision ID: dba902d88c90
Revises: 9311d6fb05a5
Create Date: 2025-04-08 11:12:03.662921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba902d88c90'
down_revision = '9311d6fb05a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_fijo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.drop_column('es_fijo')

    # ### end Alembic commands ###
