"""Crear tabla asignaturas_profesores_clases

Revision ID: f36ab67a420d
Revises: 47ace0ff34b7
Create Date: 2025-04-08 16:14:57.115796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f36ab67a420d'
down_revision = '47ace0ff34b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unido_con_clase_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ultima_modificacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('dia',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('hora',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'clases', ['unido_con_clase_id'], ['id'])
        batch_op.drop_column('fecha_modificacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_modificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('hora',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('dia',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('ultima_modificacion')
        batch_op.drop_column('unido_con_clase_id')

    # ### end Alembic commands ###
